version: '3'
services:
  rss-to-db:
    container_name: "rsstodb"
    image: "rss-to-db:lastest"
    env_file:
     - .env
    depends_on:
    - "mongo"
    build: .
    volumes:
      - "./data:/data"

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    #environment:
    #  - MONGO_DATA_DIR=/data/db
    #  - MONGO_LOG_DIR=/dev/null
    #volumes:
    #  - ./data/db:/data/db
    command: mongod --logpath=/dev/null # --quiet
